server:
  port: 8002

spring:
  application:
    name: TEST-PROVIDER   #服务名称，随意取
  profiles:
    active: redis,dev
  cloud:
    # 网关配置在nacos中配置
    gateway:
      enabled: true
      discovery: # 开启自动
        locator:
          enabled: true #是否与服务注册于发现组件结合，通过 serviceId 转发到具体的服务
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）

  #session:
  #  store-type: redis
#
  #redis:
  #  database: 1
  #  server:
  #    database:
  #    pattern: cluster
  #    nodes: 192.168.30.168:6380,192.168.30.168:6381,192.168.30.168:6382,192.168.30.168:6383,192.168.30.168:6384,192.168.30.168:6385
  #    password:
  #    maxIdle: 8
  #    minIdle: 4
  #    maxTotal: 8
  #    maxWaitMillis: 6000
  #    timeOut: 6000


#eureka:
#  client:
#    enabled: true
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka #注册到Eureka的地址
