server:
  port: 8889

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    # 网关配置在nacos中配置
    gateway:
      enabled: true
      discovery: # 开启自动
        locator:
          enabled: true #是否与服务注册于发现组件结合，通过 serviceId 转发到具体的服务
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）
    # 远程配置时需要关闭 start
    #  routes:
    #    - id: provider
    #      uri: lb://cloud-service-provider
    #      predicates:
    #        - Path=/cloud-provider/**    # 断言：路径相匹配的进行路由
    #        # filters:
    #        # StripPrefix 数字表示要截断的路径的数量
    #        #- StripPrefix=1
    #    - id: consumer
    #      uri: lb://cloud-service-consumer
    #      predicates:
    #        - Path=/cloud-consumer/**
    #      filters:
    #        - StripPrefix=1
    #  discovery:
    #    server-addr: 192.168.30.168:8848
    # 远程配置时需要关闭 end

    #nacos:
    #  #这个是注册中心
    #  discovery:
    #    server-addr: 192.168.30.168:8848
    #    service: gateway-router
    #    namespace:
#
    #  config:
    #    name: gateway-dev
    #    namespace: fe693ed2-e126-4986-945e-615755ecc0bd
    #    server-addr: 192.168.30.168:8848
    #    file-extension: yaml
    #    group: DEFAULT_GROUP_DEV
    #    username: nacos
    #    password: nacos
    #    dynamic:
    #      enabled: true

# 动态路由配置
#route:
#  dynamic:
#    enabled: true
#    namespace:
#    dataId: gateway_route
#    group: DEFAULT_GROUP
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

