spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #id-generate: uuid
      #allowMultiQueries=true  批量插入防止字段重复报错  ,characterEncoding 字符集;
      #serverTimezone 时区，不可省略，否则timezone有bug，
      #url: jdbc:mysql://192.168.3.152:2881/zszqsit?allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      #url: jdbc:mysql://192.168.70.168:3306/cpdev?allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      url: jdbc:mysql://192.168.30.168:3307/ztj?allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      #username: abs
      #password: JoyinTech1805
      username: ztj
      password: ztj
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      driver-class-name: com.mysql.cj.jdbc.Driver
      #driver-class-name: com.mysql.cj.jdbc.Driver
      filters: log4j2
      maxActive: 200
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStaents: true
      maxPoolPreparedStaentPerConnectionSize: 200
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 200
      removeAbandoned: false
      #removeAbandonedTimeout: 180
      #logAbandoned: true
      connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=1000;database.pool.logSlowSql=false
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
