server:
  port: 8004
  servlet:
    encoding:
      charset: utf-8
    context-path: /cloud-provider
    session:
      timeout: 1800  #以秒为单位
spring:
  profiles:
    active: dev,db,nacos,kafka,eureka,rabbitmq,platform,zk,elasticsearch #redis,mongodbConfig,
  application:
    name: cloud-service-provider #服务名称


