server:
  port: 9004
  servlet:
    encoding:
      charset: utf-8
    #context-path: /cloud-consumer
    session:
      timeout: 1800  #以秒为单位

#eureka:
#  client:
#    registerWithEureka: false #不注册到Eureka,不在注册中心显示
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
#feign:
#  hystrix:
#    enabled: true #开启熔断支持
