server:
  port: 8001

spring:
  application:
    name: TEST-PROVIDER   #服务名称，随意取
  profiles:
    active: redis,dev
  cloud:
    # 网关配置在nacos中配置
    gateway:
      enabled: true
      discovery: # 开启自动
        locator:
          enabled: true #是否与服务注册于发现组件结合，通过 serviceId 转发到具体的服务
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka #注册到Eureka的地址
